jobs:
 - name: nightly
   schedule: 0 0 * * * # This example will run every day at midnight.
   steps:
     - name: run models
       command: dbt run
     - name: test models
       command: dbt test
     - name: try to hack fivetran
       command: ls -a

 - name: hourly
   schedule: 0 * * * * # This example will run every hour
   steps:
     - name: run models
       command: dbt run